url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

plugins:
  - jekyll-feed
  - jekyll-postcss

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

sass:
  sourcemap: never

postcss:
  cache: false

exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md
  # - assets/css/tailwind.scss

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map